-- TennisRank ladder v1
-- Designed against the live TennisRank Supabase schema on 2026-08-15.
-- `public.profiles.id` is the authoritative app identity link.
-- The browser must NEVER receive the service-role key. Vercel server endpoints are trusted writers.

create extension if not exists pgcrypto;

create table if not exists public.team_settings (
  team_gender text primary key check (team_gender in ('boys', 'girls')),
  max_challenge_distance integer not null default 3 check (max_challenge_distance between 1 and 10),
  cooldown_hours integer not null default 0 check (cooldown_hours >= 0),
  response_deadline_hours integer not null default 48 check (response_deadline_hours > 0),
  challenge_expiration_hours integer not null default 168 check (challenge_expiration_hours > 0),
  injury_rank_protection boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.team_settings (team_gender)
values ('boys'), ('girls')
on conflict (team_gender) do nothing;

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid unique references public.profiles(id) on delete set null,
  display_name text not null,
  team_gender text not null check (team_gender in ('boys', 'girls')),
  grade_level integer check (grade_level between 9 and 12),
  division text not null default 'varsity' check (division in ('varsity', 'jv')),
  active_status text not null default 'active' check (active_status in ('active', 'injured', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ladder_entries (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null unique references public.players(id) on delete cascade,
  team_gender text not null check (team_gender in ('boys', 'girls')),
  rank_position integer not null check (rank_position > 0),
  previous_rank_position integer check (previous_rank_position > 0),
  status text not null default 'available' check (status in ('available', 'challenge_pending', 'injury_hold')),
  updated_at timestamptz not null default now(),
  constraint ladder_entries_gender_rank_unique unique (team_gender, rank_position) deferrable initially deferred
);

create table if not exists public.challenges (
  id uuid primary key default gen_random_uuid(),
  challenger_id uuid not null references public.players(id) on delete restrict,
  defender_id uuid not null references public.players(id) on delete restrict,
  team_gender text not null check (team_gender in ('boys', 'girls')),
  status text not null default 'pending_response' check (status in (
    'pending_response', 'accepted', 'scheduled', 'played', 'score_submitted',
    'pending_coach_approval', 'verified', 'declined', 'cancelled', 'expired', 'rejected'
  )),
  proposed_times jsonb not null default '[]'::jsonb,
  scheduled_for timestamptz,
  court_location text,
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  completed_at timestamptz,
  constraint challenger_must_differ_from_defender check (challenger_id <> defender_id)
);

create table if not exists public.challenge_matches (
  id uuid primary key default gen_random_uuid(),
  challenge_id uuid not null unique references public.challenges(id) on delete cascade,
  score_summary text not null,
  winner_id uuid not null references public.players(id) on delete restrict,
  approval_status text not null default 'pending' check (approval_status in ('pending', 'verified', 'rejected')),
  submitted_by_profile_id uuid references public.profiles(id) on delete set null,
  verified_by_profile_id uuid references public.profiles(id) on delete set null,
  submitted_at timestamptz not null default now(),
  verified_at timestamptz
);

create table if not exists public.rank_history (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  old_rank integer not null check (old_rank > 0),
  new_rank integer not null check (new_rank > 0),
  reason text not null check (reason in ('challenge', 'manual', 'injury_restore', 'import')),
  challenge_match_id uuid references public.challenge_matches(id) on delete set null,
  changed_by_profile_id uuid references public.profiles(id) on delete set null,
  changed_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  action_type text not null,
  target_type text not null,
  target_id text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists players_team_gender_idx on public.players (team_gender);
create index if not exists ladder_entries_team_rank_idx on public.ladder_entries (team_gender, rank_position);
create index if not exists challenges_team_status_idx on public.challenges (team_gender, status, created_at desc);
create index if not exists challenges_challenger_idx on public.challenges (challenger_id, status);
create index if not exists challenges_defender_idx on public.challenges (defender_id, status);
create index if not exists rank_history_player_time_idx on public.rank_history (player_id, changed_at desc);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);

alter table public.team_settings enable row level security;
alter table public.players enable row level security;
alter table public.ladder_entries enable row level security;
alter table public.challenges enable row level security;
alter table public.challenge_matches enable row level security;
alter table public.rank_history enable row level security;
alter table public.audit_logs enable row level security;

-- The live TennisRank project intentionally exposes its existing private tables only to
-- postgres/service_role. Match that model explicitly because new Supabase projects no longer
-- automatically expose newly-created public tables through the Data API.
revoke all on table public.team_settings from anon, authenticated;
revoke all on table public.players from anon, authenticated;
revoke all on table public.ladder_entries from anon, authenticated;
revoke all on table public.challenges from anon, authenticated;
revoke all on table public.challenge_matches from anon, authenticated;
revoke all on table public.rank_history from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;

grant select, insert, update, delete on table public.team_settings to service_role;
grant select, insert, update, delete on table public.players to service_role;
grant select, insert, update, delete on table public.ladder_entries to service_role;
grant select, insert, update, delete on table public.challenges to service_role;
grant select, insert, update, delete on table public.challenge_matches to service_role;
grant select, insert, update, delete on table public.rank_history to service_role;
grant select, insert, update, delete on table public.audit_logs to service_role;

grant usage, select on sequence public.rank_history_id_seq to service_role;
grant usage, select on sequence public.audit_logs_id_seq to service_role;

-- Create a challenge through a single database transaction. Locking both ladder rows prevents
-- simultaneous requests from putting the same player into two open challenges.
create or replace function public.create_ladder_challenge(
  p_challenger_profile_id uuid,
  p_defender_player_id uuid,
  p_proposed_times jsonb default '[]'::jsonb
) returns uuid
language plpgsql
set search_path = public
as $$
declare
  v_challenge_id uuid;
  v_challenger_id uuid;
  v_challenger_team text;
  v_defender_team text;
  v_challenger_rank integer;
  v_defender_rank integer;
  v_challenger_status text;
  v_defender_status text;
  v_max_distance integer;
begin
  select p.id, le.team_gender, le.rank_position, le.status
    into v_challenger_id, v_challenger_team, v_challenger_rank, v_challenger_status
  from public.players p
  join public.ladder_entries le on le.player_id = p.id
  where p.profile_id = p_challenger_profile_id
    and p.active_status = 'active'
  for update of le;

  if v_challenger_id is null then
    raise exception 'Challenger profile is not linked to an active ladder player';
  end if;

  select le.team_gender, le.rank_position, le.status
    into v_defender_team, v_defender_rank, v_defender_status
  from public.players p
  join public.ladder_entries le on le.player_id = p.id
  where p.id = p_defender_player_id
    and p.active_status = 'active'
  for update of le;

  if v_defender_rank is null then
    raise exception 'Defender is not an active ladder player';
  end if;

  if v_challenger_id = p_defender_player_id then
    raise exception 'A player cannot challenge themselves';
  end if;

  if v_challenger_team <> v_defender_team then
    raise exception 'Players must be on the same ladder';
  end if;

  if v_challenger_status <> 'available' or v_defender_status <> 'available' then
    raise exception 'Both players must be available';
  end if;

  select max_challenge_distance into v_max_distance
  from public.team_settings
  where team_gender = v_challenger_team;

  v_max_distance := coalesce(v_max_distance, 3);

  if v_challenger_rank - v_defender_rank < 1
     or v_challenger_rank - v_defender_rank > v_max_distance then
    raise exception 'Defender is outside the allowed challenge range';
  end if;

  if exists (
    select 1
    from public.challenges c
    where c.status in ('pending_response', 'accepted', 'scheduled', 'played', 'score_submitted', 'pending_coach_approval')
      and (
        c.challenger_id in (v_challenger_id, p_defender_player_id)
        or c.defender_id in (v_challenger_id, p_defender_player_id)
      )
  ) then
    raise exception 'One of these players already has an open challenge';
  end if;

  insert into public.challenges (challenger_id, defender_id, team_gender, proposed_times)
  values (v_challenger_id, p_defender_player_id, v_challenger_team, coalesce(p_proposed_times, '[]'::jsonb))
  returning id into v_challenge_id;

  update public.ladder_entries
  set status = 'challenge_pending', updated_at = now()
  where player_id in (v_challenger_id, p_defender_player_id);

  insert into public.audit_logs (actor_profile_id, action_type, target_type, target_id, metadata)
  values (
    p_challenger_profile_id,
    'create_challenge',
    'challenge',
    v_challenge_id::text,
    jsonb_build_object('challenger_id', v_challenger_id, 'defender_id', p_defender_player_id)
  );

  return v_challenge_id;
end;
$$;

-- Coach approval is also a single transaction. If the challenger wins, they take the defender's
-- rank and every player in between shifts down one position. If the defender wins, ranks stay put.
create or replace function public.verify_challenge_match(
  p_match_id uuid,
  p_coach_profile_id uuid
) returns void
language plpgsql
set search_path = public
as $$
declare
  v_challenge_id uuid;
  v_challenger_id uuid;
  v_defender_id uuid;
  v_winner_id uuid;
  v_team_gender text;
  v_challenger_rank integer;
  v_defender_rank integer;
  v_old_rank integer;
  v_new_rank integer;
  v_player_id uuid;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_coach_profile_id and role = 'admin'
  ) then
    raise exception 'Coach/admin profile required';
  end if;

  select cm.challenge_id, cm.winner_id, c.challenger_id, c.defender_id, c.team_gender
    into v_challenge_id, v_winner_id, v_challenger_id, v_defender_id, v_team_gender
  from public.challenge_matches cm
  join public.challenges c on c.id = cm.challenge_id
  where cm.id = p_match_id
    and cm.approval_status = 'pending'
  for update of cm, c;

  if v_challenge_id is null then
    raise exception 'Pending challenge match not found';
  end if;

  if v_winner_id not in (v_challenger_id, v_defender_id) then
    raise exception 'Winner must be the challenger or defender';
  end if;

  select rank_position into v_challenger_rank
  from public.ladder_entries
  where player_id = v_challenger_id and team_gender = v_team_gender
  for update;

  select rank_position into v_defender_rank
  from public.ladder_entries
  where player_id = v_defender_id and team_gender = v_team_gender
  for update;

  if v_challenger_rank is null or v_defender_rank is null then
    raise exception 'Both challenge players must be ranked';
  end if;

  if v_defender_rank >= v_challenger_rank then
    raise exception 'Defender must be ranked above challenger';
  end if;

  set constraints ladder_entries_gender_rank_unique deferred;

  if v_winner_id = v_challenger_id then
    for v_player_id, v_old_rank in
      select player_id, rank_position
      from public.ladder_entries
      where team_gender = v_team_gender
        and rank_position between v_defender_rank and v_challenger_rank
      order by rank_position
      for update
    loop
      if v_player_id = v_challenger_id then
        v_new_rank := v_defender_rank;
      else
        v_new_rank := v_old_rank + 1;
      end if;

      update public.ladder_entries
      set previous_rank_position = v_old_rank,
          rank_position = v_new_rank,
          updated_at = now()
      where player_id = v_player_id;

      insert into public.rank_history (
        player_id, old_rank, new_rank, reason, challenge_match_id, changed_by_profile_id
      ) values (
        v_player_id, v_old_rank, v_new_rank, 'challenge', p_match_id, p_coach_profile_id
      );
    end loop;
  end if;

  update public.ladder_entries
  set status = 'available', updated_at = now()
  where player_id in (v_challenger_id, v_defender_id);

  update public.challenge_matches
  set approval_status = 'verified',
      verified_by_profile_id = p_coach_profile_id,
      verified_at = now()
  where id = p_match_id;

  update public.challenges
  set status = 'verified', completed_at = now()
  where id = v_challenge_id;

  insert into public.audit_logs (
    actor_profile_id, action_type, target_type, target_id, metadata
  ) values (
    p_coach_profile_id,
    'verify_challenge_match',
    'challenge_match',
    p_match_id::text,
    jsonb_build_object(
      'challenge_id', v_challenge_id,
      'winner_id', v_winner_id,
      'challenger_id', v_challenger_id,
      'defender_id', v_defender_id,
      'team_gender', v_team_gender
    )
  );
end;
$$;

-- Functions in public are executable by PUBLIC by default. Explicitly close them and permit only
-- the trusted server role to invoke them.
revoke all on function public.create_ladder_challenge(uuid, uuid, jsonb) from public, anon, authenticated;
revoke all on function public.verify_challenge_match(uuid, uuid) from public, anon, authenticated;
grant execute on function public.create_ladder_challenge(uuid, uuid, jsonb) to service_role;
grant execute on function public.verify_challenge_match(uuid, uuid) to service_role;
